### ISSUE TITLE
How to make the chemical calibration preprocessing software available?

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/ProteoformSuite#238]
I feel like erring on the side of simplicity for this first paper; if we don't use chemical lock-mass for any of the vignettes in this first PS paper, I think we should defer integrating that feature until we publish results that used it (mitochondria paper?). The yeast unlabeled data might have it, so I'm looking into that.

When we do integrate it:
* Should we integrate Stefan's code to pick out these features automatically?

**Comment by acesnik** [comment]
Not going to include this in the first PS paper. I think maybe we could phrase this in a paper (e.g. Sean's) as "We preprocessed the chemical calibration peaks in the RAW files using in-house software."

**Comment by lschaffer2** [comment]
Yeah, I think for Sean's and even yours you could just mention chemical lock mass was used to calibrate. Also when we merge my top-down  changes in, I integrated calibration (both w/ topdown hits and lock mass peptide)

**Comment by lschaffer2** [comment]
Addressed in #424
