### ISSUE TITLE
WPF/XAML application

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/ProteoformSuite#311]

**Comment by acesnik** [comment]
There's some cool JavaScript functionality for cytoscape that might be useful. http://js.cytoscape.org/

**Comment by acesnik** [comment]
Still an project option

**Comment by acesnik** [comment]
# Redesigning Proteoform Suite
* "Results" menu now becomes a column of lollipops for each step in one of four workflows: Standard, Standard Quantification, Top-Down, or Top-Down Quantification
* Make a "Run" button in the same place of each step, in the lower left hand corner
* New toolbar (File, Open, Save, Help)

![mvimg_20180403_152341](https://user-images.githubusercontent.com/16342951/38274461-77216eb0-3754-11e8-8ce1-3eb90af50065.jpg)

**Comment by lschaffer2** [comment]
Merged in #556
