### ISSUE TITLE
Improving manual mass shifting performance

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/ProteoformSuite#323]
Taken from Lollipop.regroup_components:

Could be improved. Used for manual mass shifting.
* Idea 1: Start with Components -- have them find the most intense nearby component. Then, go through and correct edge cases that aren't correct.
* Idea 2: Use the assumption that proteoforms distant to the manual shift will not regroup.
* Idea 2.1: Put the shifted proteoforms, plus some range from the min and max masses in there, and reaggregate the components with the aggregate_proteoforms algorithm.

**Comment by lschaffer2** [comment]
For identified families, since you added identifying experimentals, we  could automate mass shifting in EE for identified experimentals

**Comment by acesnik** [comment]
True! I might try to keep the theoretical references in a [linked list](https://msdn.microsoft.com/library/he2s3bh7(v=vs.110).aspx), then, so we can tell how far away it is from the database reference.

**Comment by acesnik** [comment]
Performance was improved by parallelizing aggregation, in particular.
