### ISSUE TITLE
MSDecon input functionality

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/ProteoformSuite#338]
It would be nice for the papers to add the option to input MS-Decon results... then we can say that we used thermo software but PS is able to be used with this free software

**Comment by acesnik** [comment]
Does it work nicely, i.e. read in components, and they all more or less work the same, or would we have to change some of the heuristics/algorithms we're using? I'm especially worried about the missed monoisotopics and harmonics being problematic. We don't have unit testing for that bit of code, and it could introduce subtle errors.

**Comment by acesnik** [comment]
Also, does it deconvolute NeuCode pairs? From our first pass at looking at deconvolution software, I think Thermo's software won out in distinguishing NeuCode pair members.
