### ISSUE TITLE
Verifying identified experimentals with database lookup and making annulus to indicate verification

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/ProteoformSuite#387]
Look back into the Protein entries generated from the UniProt XML to check whether the PTM sets of identified proteoforms are possible, given the database, or whether they represent additional PTMs.

**Comment by lschaffer2** [comment]
Add annulus to verified experimentals

**Comment by lschaffer2** [comment]
Added option to see uniprot annotated mods for the mods on that proteoforms
