### ISSUE TITLE
Low mass error proteoform matches are being assigned to dubious unmodified theoreticals

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/ProteoformSuite#388]
Leah's reported a few instances where a theoretical (T) with an oxidation (ox) is being assigned to another theoretical that is unmodified, when the match with T+ox is much closer.

e.g.
T1+ox     mass error = 0.0001
T2           mass error = 0.05
   
An idea of how to handle this is to bin matches by mass error before choosing the least complex PTM set. We need to find a way to handle the inital objective of choosing the least complex PTM set, which are instances like such:

PTM set mass = 0.01; mass error = 0; T1 + ox - (ox then loss of oxidized methionine sidechain)
PTM set mass = 0 (unmodified); mass error = 0.01; T1

**Comment by lschaffer2** [comment]
Added option to match to more than one theo from different gene, which would solve this issue
