### ISSUE TITLE
"Proteoform Family Assignment" Dropdown menus are narrow.

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/ProteoformSuite#430]
Complete words of the options could not be seen.
![ps2 2issue1](https://user-images.githubusercontent.com/20566230/28897402-274cda28-77a6-11e7-934e-2abd099188b0.png)

**Comment by acesnik** [comment]
Thanks for the feedback. I'll improve this in my next batch of changes.

**Comment by acesnik** [comment]
addressed in https://github.com/smith-chem-wisc/proteoform-suite/pull/434
