### ISSUE TITLE
Unmodified ET pairs showing up as "water adduct; water loss"

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/ProteoformSuite#446]

**Comment by acesnik** [comment]
Is this because of the issue you noted in the pull request? https://github.com/smith-chem-wisc/ProteoformSuite/pull/443

**Comment by lschaffer2** [comment]
Yes - it wasn't including unmodified as a possible ptmset

**Comment by acesnik** [comment]
Okay. Good to know!

**Comment by acesnik** [comment]
Were you seeing this for TopDown ones or Experimental?

**Comment by lschaffer2** [comment]
It was only for experimental

**Comment by acesnik** [comment]
Is this still a problem, or can we close this one?
