### ISSUE TITLE
Configuring the schema for Cytoscape

### ISSUE THREAD

**Issue by weedkiller** [smith-chem-wisc/ProteoformSuite#449]
Hello, this is such a rare lib!!

I am trying to use this with a modification for the network with some data... can you please share some guidance on what the data scheme/model is for the nodes and edges.

Thanks

**Comment by acesnik** [comment]
Hi there! The cytoscape diagrams use four types of files, an edge table (for network connections), a node table (for node information), a style XML file, and a script that can be run under `Tools -> Execute Command File` inside Cytoscape. Are you trying to use the `CytoscapeScript` class for another application?

**Comment by weedkiller** [comment]
@acesnik thanks for the response.

I wanted to model a network topology on your platform, using C# back end.. I was trying to convert these objects.

Is there a list of the definitions in JSON for these objects.

thanks

**Comment by acesnik** [comment]
Sorry for the delay. I would have liked to have helped, but I have no experience with JSON and no idea how to help.
