### ISSUE TITLE
If the same file is in identification and quantification, "change file" actions don't always address the right one

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/ProteoformSuite#452]

**Comment by acesnik** [comment]
Need to add indicator for Identification or Quantification to the line.

**Comment by lschaffer2** [comment]
Don't we not allow files with the same name to be added?

**Comment by acesnik** [comment]
Files with the same name can be added to Identification and Quantification. This is how we would do 2:1 NeuCode quant validation and label free quantification.

**Comment by acesnik** [comment]
Addressing in https://github.com/smith-chem-wisc/ProteoformSuite/pull/479
