### ISSUE TITLE
Last component not read in

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/ProteoformSuite#454]
In ComponentReader I think we should add "add_component(new_component);" at line 81

**Comment by acesnik** [comment]
Isn't this handled at line 79? https://github.com/smith-chem-wisc/ProteoformSuite/blob/master/ProteoformSuiteInternal/ComponentReader.cs#L79

**Comment by lschaffer2** [comment]
Oops -- this was changed when merged from upstream on td branch because excel reader different
