### ISSUE TITLE
Decoy proteoforms should have decoy sequences

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/ProteoformSuite#461]
Currently, decoy proteoform sequences being set to corresponding theoretical's actual protein sequence

**Comment by lschaffer2** [comment]
***need to unparallelize shuffled_proteins loop for taking hunks off of giantprotein

**Comment by acesnik** [comment]
Why does it need to be unparallelized? Isn't substring thread-safe?

**Comment by lschaffer2** [comment]
If you want the decoy database to be the same each time with the seed

**Comment by acesnik** [comment]
I don't see it; the Random object used for shuffling before that loop is seeded. Isn't the only issue here setting the decoy TheoreticalProteoform objects to have the correct sequence, so that the heuristics using that sequence are correct.

**Comment by acesnik** [comment]
Totally on board! Thanks for explaining. `prevLength` isn't thread-safe!

**Comment by lschaffer2** [comment]
Fixed in #424
