### ISSUE TITLE
Should be unparallelized

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/ProteoformSuite#470]
https://github.com/smith-chem-wisc/ProteoformSuite/blob/d2fc6708c03aee23f752b6b44c3ed3254f95409f/ProteoformSuiteInternal/TheoreticalProteoformDatabase.cs#L61

If I have >1 database with mods, and the mods list gets modified while in loadproteinxml, I get exception thrown that collection was modified

**Comment by acesnik** [comment]
I couldn't reproduce this exception. I put in two databases with mods, and it finished making the databases.
![image](https://user-images.githubusercontent.com/16342951/34034000-3a9c9a04-e142-11e7-82ba-e748c2302e9c.png)

**Comment by lschaffer2** [comment]
I think it was if I had a gptmd database with the mods and a ptmlist, or 2 gptmd databases

**Comment by acesnik** [comment]
These were two GPTMD databases. We should try the GPTMD + separate ptmlist combo to double check. Otherwise, might it be an issue on your branch for some reason?
