### ISSUE TITLE
Results display issues for components, proteoforms, families

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/ProteoformSuite#476]
- It would be nice to have a "Raw components assigned to this proteoform" column somewhere towards the end of the analysis (for identified, unidentified, orphan proteoforms)
- In the "Proteoform Family Assignment" page, the "PTM Description" shows "Unmodified" as the default option; when the mass-relationship is complex (many modifications), the "PTM Description" shows "Unmodified" (the relationship shows up correctly in the Cytoscape graphics)

**Comment by lschaffer2** [comment]
crash if export families without having constructed them

**Comment by acesnik** [comment]
If you still have it running, could you take a screenshot of the latter issue?
