### ISSUE TITLE
Option to read .fasta file

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/ProteoformSuite#477]
tried to use a .fasta in proteoformsuite without some kind of additional PTM list and got a crash, I assume that is not allowed but a meaningful error message would be nice

**Comment by acesnik** [comment]
Adding a notification of this limitation in next pull request. Marked as new feature for a later date.
![image](https://user-images.githubusercontent.com/16342951/34026993-69594a54-e11f-11e7-96c2-fc62e1c65504.png)

**Comment by acesnik** [comment]
Thanks for posting the suggestion, @rmillikin!

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/ProteoformSuite/pull/479
