### ISSUE TITLE
Cannot Revisit Previous Result Pages

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/ProteoformSuite#483]
In the recent versions of Proteoform Suite (3.0, and unreleased versions for deconvolution purposes), sometimes I cannot go back to a "Results" page when that page has already been viewed. e.g. After viewing EE page, the "theoretical database" page cannot show. If it manages to show again sometime, the ET page can become inactive. I usually close the program and redo everything again, but this has been a bit inconvenient recently.

**Comment by lschaffer2** [comment]
Does this happen in version 0.3.1 on your computer?

**Comment by seanydai** [comment]
This still happens in 0.3.1, but seems to be less often.

**Comment by lschaffer2** [comment]
I think no longer a problem with new results pages in WPF
