### ISSUE TITLE
How is Theoretical Mass Calculated?

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/ProteoformSuite#489]
I was looking at the theoretical proteoforms made in Proteoform Suite, and saw that the MW values of the entries are a bit different from the values found on the UniProt website. Could someone remind me of how it is calculated again? It made sense to me at some point, but I forgot how. I might be missing something here (NeuCode Lysine, fixed CAM, N,C terminal structure). I have picked 5 examples of E. coli theoreticals, which can be found in the attached table.
[Theoretical Mass1.xlsx](https://github.com/smith-chem-wisc/ProteoformSuite/files/1746016/Theoretical.Mass1.xlsx)
Thanks!

**Comment by lschaffer2** [comment]
The uniprot mass doesn’t include carbamidpmethylation of C. Does this explain those differences?

**Comment by lschaffer2** [comment]
Hi Sean, I think the UniProt mass is the average, not the monoisotopic mass. I took the M-cleaved sequence from the first example, and here's what a mass calculator says: 
![image](https://user-images.githubusercontent.com/16846041/36548410-d891b79a-17b5-11e8-8393-a22a75e242c4.png)
