### ISSUE TITLE
Add Methionine notch in ET comparison

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/ProteoformSuite#509]
I don't usually see the retained methionine peak (+131.0405 Da) in ET comparison. I hope to see it being included in the notch list. Thanks.

**Comment by lschaffer2** [comment]
Do you see a 131 peak in the "raw ET histogram" image or the EE image? I think 131 should show up because amino acid loss/gain are mods with good ranks

**Comment by seanydai** [comment]
I do not see a 131 peak in ET histogram, but it is common in EE histogram.

**Comment by lschaffer2** [comment]
Fixed in #528
