### ISSUE TITLE
total family number/proteoform number do not add up

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/ProteoformSuite#512]
I did several runs, and found that whenever TD hit report is loaded for analysis, in the result page, the number of identified, ambiguous, unidentified families do not add up to the total family number. Same issue with proteoform numbers.
The numbers add up when just using intact-mass data.
Test data in Leah's folder Issue 512.
![2018-05-07 2 19 23](https://user-images.githubusercontent.com/20566230/39720524-4333c85a-5202-11e8-9921-1adb327cd992.png)

**Comment by lschaffer2** [comment]
Fixed the family # bug, will be in next release. Thank you for catching it!!

**Comment by lschaffer2** [comment]
Proteoform #'s should add up now with pull request #511 . This issue was I linked top-down proteoforms to genes at some point and this messed up how we calculate #'s, so it double counted some families/proteoforms.

**Comment by seanydai** [comment]
Great! Thanks for fixing this.
