### ISSUE TITLE
Unable to run ProteoWPFSuite.exe in v0.4.1

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/ProteoformSuite#571]
v0.4.0 works fine for me.

Also no icon in the new release?
![image](https://user-images.githubusercontent.com/16883585/117176619-109b8e00-ad9e-11eb-92c8-418516210fb5.png)

**Comment by acesnik** [comment]
Pretty strange! I see the same thing.

I rebuilt PS at that commit (e94716c), and it's looking more normal and opening up.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/16342951/127206412-8f0f53b8-b3fa-4ec7-8583-2f6bcd0b3285.png">

Just zipped that working rebuilt one and placed it in the release here and deleted the old one. https://github.com/smith-chem-wisc/ProteoformSuite/releases/tag/0.4.1

**Comment by leahvschaffer** [comment]
Weird maybe something went wrong with my build... thanks anthony!!!

**Comment by acesnik** [comment]
No problem! 😄
